name: Docker Docker3

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    run: docker build . --file Dockerfile.dev --tag docker.devusol.net/docker-react
    run: docker run -e CI=true docker.devusol.net/docker-react npm run test
